# Generated by Django 5.0.6 on 2024-07-02 13:27

import django.db.models.deletion
import toons.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toons', '0006_toons_model_favourites_toons_model_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, default=0.0)),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name=toons.models.toons_model)),
                ('image', models.ImageField(blank=True, default='1670311516_61-fashionhot-club-p-termobele-skins-64.jpg', upload_to='profile')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to='toons.toons_model')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
