# Generated by Django 5.0.6 on 2024-07-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_user'),
        ('toons', '0008_toons_model_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes_for',
            field=models.ManyToManyField(blank=True, related_name='likes_for', to='toons.toons_model'),
        ),
    ]
