# Generated by Django 5.0.6 on 2024-07-03 14:27

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_likes_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default=account.models.rand_slug, unique=True),
        ),
    ]
