# Generated by Django 5.0.6 on 2024-07-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_chat_messages_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_messages',
            name='slug',
        ),
    ]
