# Generated by Django 5.0.6 on 2024-07-30 11:19

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_private_mess_user_alter_chat_messages_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='indefecator_key',
            field=models.CharField(default=account.models.rand_key, max_length=50),
        ),
    ]
