# Generated by Django 5.0.6 on 2024-08-01 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_notification'),
        ('subscribe_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribe_payment.lvl_subscribe'),
        ),
    ]
