# Generated by Django 5.0.6 on 2024-06-24 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toons_model',
            name='image',
            field=models.ImageField(blank=True, default='1670311516_61-fashionhot-club-p-termobele-skins-64.jpg', upload_to='toons'),
        ),
        migrations.CreateModel(
            name='toon_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('year_created', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('toon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toons.toons_model')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
    ]
