# Generated by Django 5.0.6 on 2024-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toons', '0002_alter_toons_model_image_toon_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='toon_series',
            name='video',
            field=models.FileField(blank=True, default='1670311516_61-fashionhot-club-p-termobele-skins-64.jpg', null=True, upload_to='toons'),
        ),
    ]
