# Generated by Django 5.0.6 on 2024-06-24 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toons', '0003_toon_series_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toon_series',
            name='video',
            field=models.FileField(blank=True, default='1670311516_61-fashionhot-club-p-termobele-skins-64.jpg', null=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
