# Generated by Django 5.0.6 on 2024-07-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toons', '0006_toons_model_favourites_toons_model_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toons_model',
            name='likes',
        ),
    ]
