# Generated by Django 5.0.6 on 2024-07-02 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toons', '0007_remove_toons_model_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='toons_model',
            name='likes',
            field=models.ManyToManyField(blank=True, default='alex', related_name='toon_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
