# Generated by Django 5.0.6 on 2024-07-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toons', '0011_review_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_review',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='otvet',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='toons.review_review'),
        ),
    ]
