# Generated by Django 5.0.6 on 2024-08-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toons', '0012_remove_review_review_review_review_otvet'),
    ]

    operations = [
        migrations.AddField(
            model_name='toons_model',
            name='sub_lvl',
            field=models.IntegerField(default=0),
        ),
    ]
