# Generated by Django 5.0.6 on 2024-08-01 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe_payment', '0001_initial'),
        ('toons', '0014_remove_toons_model_sub_lvl_toons_model_subing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toons_model',
            name='subing',
        ),
        migrations.AddField(
            model_name='toons_model',
            name='subing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subing', to='subscribe_payment.lvl_subscribe'),
        ),
    ]
